export const countryIconResolver = {
  sweden: require('../../../theme/country-flags/sweden.png'),
  mexico: require('../../../theme/country-flags/mexico.png'),
  venezuela: require('../../../theme/country-flags/venezuela.png'),
  peru: require('../../../theme/country-flags/peru.png'),
  argentina: require('../../../theme/country-flags/argentina.png'),
  brazil: require('../../../theme/country-flags/brazil.png'),
  canada: require('../../../theme/country-flags/canada.png'),
  chile: require('../../../theme/country-flags/chile.png'),
  colombia: require('../../../theme/country-flags/colombia.png'),
  france: require('../../../theme/country-flags/france.png'),
  italy: require('../../../theme/country-flags/italy.png'),
  netherlands: require('../../../theme/country-flags/netherlands.png'),
  spain: require('../../../theme/country-flags/spain.png'),
  uk: require('../../../theme/country-flags/uk.png'),
  usa: require('../../../theme/country-flags/usa.png'),
};
